repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Укажите последнюю версию
    hooks:
      - id: trailing-whitespace
        files: \.py$
      - id: end-of-file-fixer
        language_version: "3.9"
      - id: check-yaml
        exclude: ^venv/
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: ^venv/
  - repo: https://github.com/psf/black
    # https://black.readthedocs.io/en/stable/
    rev: 24.8.0  # Укажите последнюю версию
    hooks:
      - id: black
        files: \.py$
        exclude: ^venv/
        language_version: "3.9"
  - repo: https://github.com/PyCQA/pylint
    # https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/f-string-without-interpolation.html
    rev: v3.2.7
    # plus .pylintrc
    hooks:
      - id: pylint
        language: system
        types: [python]
  - repo: https://github.com/PyCQA/isort

    rev: 5.13.2
    hooks:
      - id: isort
